module TraceViz
  module Utils
    module Colorize
      def self.colorize: (String? text, *Symbol styles) -> String?
      private def self.build_color_sequence: (Array[Symbol] styles) -> String
    end
  end
end
